image: node

stages:
  - test
  - deps

# Cache the node modules installed.
cache:
  paths:
    - node_modules/

# Lets name our Job unitTest, because that's what it's doing.
unitTest:
  # run tests and determine coverage
  stage: test
  # What scripts do we want to run?
  script:
    - npm install
    - npm run test
