image: node:14.17.0

stages:
  - test
  - deps

# Cache the node modules installed.
cache:
  paths:
    - node_modules/

# Lets name our Job unitTest, because that's what it's doing.
unitTest:
  # run tests and determine code test coverage
  stage: test
  tags:
    - test

  # Install packages for test scripts we want to run
  script:
    - npm cache clean --force
    - npm install --force
    - npm run test
