image: node:14.17.0

stages:
  - test
  - deps

# Cache the node modules installed.
cache:
  paths:
    - node_modules/

# Lets name our Job unitTest, because that's what it's doing.
unitTest:
  # run tests and determine coverage
  stage: test
  tags:
    - docker

  # Install packages for scripts we want to run
  script:
    - npm install
    - npm install @babel/core --save
    - npm cache clean --force
    - npm run test
