const fulfilment_data = {
  delivery_request: [
    {
      order_no: 'ES97ZL615-F4U',
      status: 'Pending',
      seller_name: 'Jame Merchant',
      recipient_name: 'John Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      pickup_location: 'The Chancery, Valley Rd ',
      destination_location: 'Tilisi Hub',
      distance: 20,
      order_amount: 244,
      currency: 'KSH',
      assigned_batch_no: 'BLF-O001',
      estimated_weight: 400,
      unit_per_order: 10,
      volume: 10,
      batch_no: '#13322',
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'In Transit',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      pickup_location: 'The Chancery, Valley Rd ',
      destination_location: 'Tilisi Hub',
      distance: 20,
      order_amount: 244,
      currency: 'KSH',
      assigned_batch_no: 'BLF-O001',
      estimated_weight: 400,
      unit_per_order: 10,
      volume: 10,
      batch_no: '#13322',
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      pickup_location: 'The Chancery, Valley Rd ',
      destination_location: 'Tilisi Hub',
      distance: 20,
      order_amount: 244,
      currency: 'KSH',
      assigned_batch_no: 'BLF-O001',
      estimated_weight: 400,
      unit_per_order: 10,
      volume: 10,
      batch_no: '#13322',
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'Pending',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      pickup_location: 'The Chancery, Valley Rd ',
      destination_location: 'Tilisi Hub',
      distance: 20,
      order_amount: 244,
      currency: 'KSH',
      assigned_batch_no: 'BLF-O001',
      estimated_weight: 400,
      unit_per_order: 10,
      volume: 10,
      batch_no: '#13322',
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'Received',
      seller_name: 'Jame Merchant',
      recipient_name: 'John Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      pickup_location: 'The Chancery, Valley Rd ',
      destination_location: 'Tilisi Hub',
      distance: 20,
      order_amount: 244,
      currency: 'KSH',
      assigned_batch_no: 'BLF-O001',
      estimated_weight: 400,
      unit_per_order: 10,
      volume: 10,
      batch_no: '#13322',
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'In Transit',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      pickup_location: 'The Chancery, Valley Rd ',
      destination_location: 'Tilisi Hub',
      distance: 20,
      order_amount: 244,
      currency: 'KSH',
      assigned_batch_no: 'BLF-O001',
      estimated_weight: 400,
      unit_per_order: 10,
      volume: 10,
      batch_no: '#13322',
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      pickup_location: 'The Chancery, Valley Rd ',
      destination_location: 'Tilisi Hub',
      distance: 20,
      order_amount: 244,
      currency: 'KSH',
      assigned_batch_no: 'BLF-O001',
      estimated_weight: 400,
      unit_per_order: 10,
      volume: 10,
      batch_no: '#13322',
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      pickup_location: 'The Chancery, Valley Rd ',
      destination_location: 'Tilisi Hub',
      distance: 20,
      order_amount: 244,
      currency: 'KSH',
      assigned_batch_no: 'BLF-O001',
      estimated_weight: 400,
      unit_per_order: 10,
      volume: 10,
      batch_no: '#13322',
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'Received',
      seller_name: 'Jame Merchant',
      recipient_name: 'John Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      pickup_location: 'The Chancery, Valley Rd ',
      destination_location: 'Tilisi Hub',
      distance: 20,
      order_amount: 244,
      currency: 'KSH',
      assigned_batch_no: 'BLF-O001',
      estimated_weight: 400,
      unit_per_order: 10,
      volume: 10,
      batch_no: '#13322',
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'In Transit',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      pickup_location: 'The Chancery, Valley Rd ',
      destination_location: 'Tilisi Hub',
      distance: 20,
      order_amount: 244,
      currency: 'KSH',
      assigned_batch_no: 'BLF-O001',
      estimated_weight: 400,
      unit_per_order: 10,
      volume: 10,
      batch_no: '#13322',
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      pickup_location: 'The Chancery, Valley Rd ',
      destination_location: 'Tilisi Hub',
      distance: 20,
      order_amount: 244,
      currency: 'KSH',
      assigned_batch_no: 'BLF-O001',
      estimated_weight: 400,
      unit_per_order: 10,
      volume: 10,
      batch_no: '#13322',
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      pickup_location: 'The Chancery, Valley Rd ',
      destination_location: 'Tilisi Hub',
      distance: 20,
      order_amount: 244,
      currency: 'KSH',
      assigned_batch_no: 'BLF-O001',
      estimated_weight: 400,
      unit_per_order: 10,
      volume: 10,
      batch_no: '#13322',
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'Received',
      seller_name: 'Jame Merchant',
      recipient_name: 'John Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      pickup_location: 'The Chancery, Valley Rd ',
      destination_location: 'Tilisi Hub',
      distance: 20,
      order_amount: 244,
      currency: 'KSH',
      assigned_batch_no: 'BLF-O001',
      estimated_weight: 400,
      unit_per_order: 10,
      volume: 10,
      batch_no: '#13322',
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'In Transit',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      pickup_location: 'The Chancery, Valley Rd ',
      destination_location: 'Tilisi Hub',
      distance: 20,
      order_amount: 244,
      currency: 'KSH',
      assigned_batch_no: 'BLF-O001',
      estimated_weight: 400,
      unit_per_order: 10,
      volume: 10,
      batch_no: '#13322',
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      pickup_location: 'The Chancery, Valley Rd ',
      destination_location: 'Tilisi Hub',
      distance: 20,
      order_amount: 244,
      currency: 'KSH',
      assigned_batch_no: 'BLF-O001',
      estimated_weight: 400,
      unit_per_order: 10,
      volume: 10,
      batch_no: '#13322',
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      pickup_location: 'The Chancery, Valley Rd ',
      destination_location: 'Tilisi Hub',
      distance: 20,
      order_amount: 244,
      currency: 'KSH',
      assigned_batch_no: 'BLF-O001',
      estimated_weight: 400,
      unit_per_order: 10,
      volume: 10,
      batch_no: '#13322',
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'Received',
      seller_name: 'Jame Merchant',
      recipient_name: 'John Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      pickup_location: 'The Chancery, Valley Rd ',
      destination_location: 'Tilisi Hub',
      distance: 20,
      order_amount: 244,
      currency: 'KSH',
      assigned_batch_no: 'BLF-O001',
      estimated_weight: 400,
      unit_per_order: 10,
      volume: 10,
      batch_no: '#13322',
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'In Transit',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      pickup_location: 'The Chancery, Valley Rd ',
      destination_location: 'Tilisi Hub',
      distance: 20,
      order_amount: 244,
      currency: 'KSH',
      assigned_batch_no: 'BLF-O001',
      estimated_weight: 400,
      unit_per_order: 10,
      volume: 10,
      batch_no: '#13322',
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      pickup_location: 'The Chancery, Valley Rd ',
      destination_location: 'Tilisi Hub',
      distance: 20,
      order_amount: 244,
      currency: 'KSH',
      assigned_batch_no: 'BLF-O001',
      estimated_weight: 400,
      unit_per_order: 10,
      volume: 10,
      batch_no: '#13322',
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      pickup_location: 'The Chancery, Valley Rd ',
      destination_location: 'Tilisi Hub',
      distance: 20,
      order_amount: 244,
      currency: 'KSH',
      assigned_batch_no: 'BLF-O001',
      estimated_weight: 400,
      unit_per_order: 10,
      volume: 10,
      batch_no: '#13322',
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'Received',
      seller_name: 'Jame Merchant',
      recipient_name: 'John Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      pickup_location: 'The Chancery, Valley Rd ',
      destination_location: 'Tilisi Hub',
      distance: 20,
      order_amount: 244,
      currency: 'KSH',
      assigned_batch_no: 'BLF-O001',
      estimated_weight: 400,
      unit_per_order: 10,
      volume: 10,
      batch_no: '#13322',
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'In Transit',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      pickup_location: 'The Chancery, Valley Rd ',
      destination_location: 'Tilisi Hub',
      distance: 20,
      order_amount: 244,
      currency: 'KSH',
      assigned_batch_no: 'BLF-O001',
      estimated_weight: 400,
      unit_per_order: 10,
      volume: 10,
      batch_no: '#13322',
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      pickup_location: 'The Chancery, Valley Rd ',
      destination_location: 'Tilisi Hub',
      distance: 20,
      order_amount: 244,
      currency: 'KSH',
      assigned_batch_no: 'BLF-O001',
      estimated_weight: 400,
      unit_per_order: 10,
      volume: 10,
      batch_no: '#13322',
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      pickup_location: 'The Chancery, Valley Rd ',
      destination_location: 'Tilisi Hub',
      distance: 20,
      order_amount: 244,
      currency: 'KSH',
      assigned_batch_no: 'BLF-O001',
      estimated_weight: 400,
      unit_per_order: 10,
      volume: 10,
      batch_no: '#13322',
    },
  ],

  movable_units: [
    {
      order_no: 'ES97ZL615-F4U',
      status: 'Pending',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
  ],
  inbound_batched_orders: [
    {
      order_no: 'ES97ZL615-F4U',
      status: 'Pending',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      pick_up: 'Alp Warehouse',
      destination: 'Westlands Hub',
      package_no: 20,
      batch_no: '#48920',
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'Pending',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      pick_up: 'Alp Warehouse',
      destination: 'Westlands Hub',
      package_no: 20,
      batch_no: '#48920',
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'Pending',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      pick_up: 'Alp Warehouse',
      destination: 'Westlands Hub',
      package_no: 20,
      batch_no: '#48920',
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'Pending',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      pick_up: 'Alp Warehouse',
      destination: 'Westlands Hub',
      package_no: 20,
      batch_no: '#48920',
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'Pending',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      pick_up: 'Alp Warehouse',
      destination: 'Westlands Hub',
      package_no: 20,
      batch_no: '#48920',
    },
  ],
};

export default fulfilment_data;
