const fulfilment_data = {
  movable_units: [
    {
      order_no: 'ES97ZL615-F4U',
      status: 'Pending',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
    {
      order_no: 'ES97ZL615-F4U',
      status: 'received',
      seller_name: 'Jame Merchant',
      recipient_name: 'Mike Doe',
      rider_name: 'Sendy Rider',
      rider_id: 1,
      city_name: 'Nairobi',
      time_placed: '2021-09-28T09:32:46.000Z',
      movable_unit_id: 'BLF-O001',
      hub_pickup: 'Alp Warehouse',
      hub_destination: 'Westlands Hub',
      batches_no: 10,
    },
  ],
  delivery_list: {
    message: 'delivery.list.success',
    data: {
      delivery: [
        {
          order_no: '4503459',
          amount: 3450,
          fulfilment_fee: 44,
          creation_date: '21 Jan 2022',
          fulfilment_date: '23 Aug 2021',
          status: 'paid',
          country: 'KENYA',
          currency: 'KSH',
        },
        {
          order_no: '4503459',
          amount: 3450,
          fulfilment_fee: 44,
          creation_date: '21 Jan 2022',
          fulfilment_date: '23 Aug 2021',
          status: 'paid',
          country: 'KENYA',
          currency: 'KSH',
        },
        {
          order_no: '4503459',
          amount: 3450,
          fulfilment_fee: 44,
          creation_date: '21 Jan 2022',
          fulfilment_date: '23 Aug 2021',
          status: 'paid',
          country: 'KENYA',
          currency: 'KSH',
        },
        {
          order_no: '4503459',
          amount: 3450,
          fulfilment_fee: 44,
          creation_date: '21 Jan 2022',
          fulfilment_date: '23 Aug 2021',
          status: 'paid',
          country: 'KENYA',
          currency: 'KSH',
        },
        {
          order_no: '4503459',
          amount: 3450,
          fulfilment_fee: 44,
          creation_date: '21 Jan 2022',
          fulfilment_date: '23 Aug 2021',
          status: 'paid',
          country: 'KENYA',
          currency: 'KSH',
        },
        {
          order_no: '4503459',
          amount: 3450,
          fulfilment_fee: 44,
          creation_date: '21 Jan 2022',
          fulfilment_date: '23 Aug 2021',
          status: 'paid',
          country: 'KENYA',
          currency: 'KSH',
        },
        {
          order_no: '4503459',
          amount: 3450,
          fulfilment_fee: 44,
          creation_date: '21 Jan 2022',
          fulfilment_date: '23 Aug 2021',
          status: 'paid',
          country: 'KENYA',
          currency: 'KSH',
        },
        {
          order_no: '4503459',
          amount: 3450,
          fulfilment_fee: 44,
          creation_date: '21 Jan 2022',
          fulfilment_date: '23 Aug 2021',
          status: 'paid',
          country: 'KENYA',
          currency: 'KSH',
        },
        {
          order_no: '4503459',
          amount: 3450,
          fulfilment_fee: 44,
          creation_date: '21 Jan 2022',
          fulfilment_date: '23 Aug 2021',
          status: 'paid',
          country: 'KENYA',
          currency: 'KSH',
        },
        {
          order_no: '4503459',
          amount: 3450,
          fulfilment_fee: 44,
          creation_date: '21 Jan 2022',
          fulfilment_date: '23 Aug 2021',
          status: 'paid',
          country: 'KENYA',
          currency: 'KSH',
        },
        {
          order_no: '4503459',
          amount: 3450,
          fulfilment_fee: 44,
          creation_date: '21 Jan 2022',
          fulfilment_date: '23 Aug 2021',
          status: 'paid',
          country: 'KENYA',
          currency: 'KSH',
        },
        {
          order_no: '4503459',
          amount: 3450,
          fulfilment_fee: 44,
          creation_date: '21 Jan 2022',
          fulfilment_date: '23 Aug 2021',
          status: 'paid',
          country: 'KENYA',
          currency: 'KSH',
        },
        {
          order_no: '4503459',
          amount: 3450,
          fulfilment_fee: 44,
          creation_date: '21 Jan 2022',
          fulfilment_date: '23 Aug 2021',
          status: 'paid',
          country: 'KENYA',
          currency: 'KSH',
        },
      ],
      pagination: {
        current_page: 0,
        max: 100,
        page_count: 1,
      },
    },
    errors: [],
  },
  invoice_list: {
    message: 'invoice.list.success',
    data: {
      invoice: [
        {
          invoice_no: '4503459',
          creation_date: '21 Jan 2022',
          invoice_amount: 3000,
          total_deliveries: 10,
          country: 'KENYA',
          currency: 'KSH',
        },
        {
          invoice_no: '4503459',
          creation_date: '21 Jan 2022',
          invoice_amount: 3000,
          total_deliveries: 10,
          country: 'KENYA',
          currency: 'KSH',
        },
        {
          invoice_no: '4503459',
          creation_date: '21 Jan 2022',
          invoice_amount: 3000,
          total_deliveries: 10,
          country: 'KENYA',
          currency: 'KSH',
        },
        {
          invoice_no: '4503459',
          creation_date: '21 Jan 2022',
          invoice_amount: 3000,
          total_deliveries: 10,
          country: 'KENYA',
          currency: 'KSH',
        },
        {
          invoice_no: '4503459',
          creation_date: '21 Jan 2022',
          invoice_amount: 3000,
          total_deliveries: 10,
          country: 'KENYA',
          currency: 'KSH',
        },
        {
          invoice_no: '4503459',
          creation_date: '21 Jan 2022',
          invoice_amount: 3000,
          total_deliveries: 10,
          country: 'KENYA',
          currency: 'KSH',
        },
        {
          invoice_no: '4503459',
          creation_date: '21 Jan 2022',
          invoice_amount: 3000,
          total_deliveries: 10,
          country: 'KENYA',
          currency: 'KSH',
        },
        {
          invoice_no: '4503459',
          creation_date: '21 Jan 2022',
          invoice_amount: 3000,
          total_deliveries: 10,
          country: 'KENYA',
          currency: 'KSH',
        },
        {
          invoice_no: '4503459',
          creation_date: '21 Jan 2022',
          invoice_amount: 3000,
          total_deliveries: 10,
          country: 'KENYA',
          currency: 'KSH',
        },
        {
          invoice_no: '4503459',
          creation_date: '21 Jan 2022',
          invoice_amount: 3000,
          total_deliveries: 10,
          country: 'KENYA',
          currency: 'KSH',
        },
        {
          invoice_no: '4503459',
          creation_date: '21 Jan 2022',
          invoice_amount: 3000,
          total_deliveries: 10,
          country: 'KENYA',
          currency: 'KSH',
        },
        {
          invoice_no: '4503459',
          creation_date: '21 Jan 2022',
          invoice_amount: 3000,
          total_deliveries: 10,
          country: 'KENYA',
          currency: 'KSH',
        },
        {
          invoice_no: '4503459',
          creation_date: '21 Jan 2022',
          invoice_amount: 3000,
          total_deliveries: 10,
          country: 'KENYA',
          currency: 'KSH',
        },
      ],
      pagination: {
        current_page: 0,
        max: 100,
        page_count: 1,
      },
    },
    errors: [],
  },
};

export default fulfilment_data;
