<template lang="html">
  <div class="row">
    <div v-if="loading_invoices" class="centre-loader">
      <invoiceLoading />
    </div>
    <div v-else class="outline-inner-data">
      <form
        id="reallocate-form"
        @submit.prevent="generate_invoice_number"
        class="form-inline"
      >
        <div class="form-group col-md-6 user-input">
          <v-select
            :options="sendyEntities"
            name="entity_name"
            label="entity_name"
            placeholder="Sendy Entities"
            class="form-control select user-billing"
            :id="`sendy_entity`"
            v-model="sendyEntity"
            :class="{
              'is-invalid': submitted && $v.sendyEntity.$error,
            }"
          >
          </v-select>
          <div
            v-if="submitted && !$v.sendyEntity.required"
            class="invalid-feedback"
          >
            Sendy Entity is required
          </div>
        </div>
        <div class="form-group col-md-6 user-input">
          <button class="btn btn-primary action-button">
            Generate Invoice Number
          </button>
        </div>
      </form>

      <div v-if="submit_status" class="response-section">
        <p class="response-text" v-if="response_status === true">
          <i class="fa fa-spinner fa-spin loader invoice-loader--align"></i>
          Processing your request ....
        </p>
        <p class="response-text" v-else-if="response_status === 'success'">
          <i
            class="fa fa-check-circle invoice-loader--align submit-success"
          ></i>
          The new invoice number generated for {{ sendyEntity.entity_name }} is
          <span class="invoice-number-highlight">
            {{ generated_invoice_no }}</span
          >
        </p>
        <p class="response-text" v-else>
          <i
            class="fa fa-exclamation-circle invoice-loader--align submit-error"
          ></i>
          {{ error_msg }}
        </p>
      </div>

      <div class="body-box col-md-12 table-content">
        <div v-if="invoice_logs.length === 0 || invoice_logs === null">
          No Records
        </div>
        <table
          class="table table-bordered table-background"
          v-if="invoice_logs.length > 0"
        >
          <thead>
            <tr>
              <td></td>
              <td>Invoice Number</td>
              <td>Sendy Entity</td>
              <td>Generated by</td>
              <td>Date Generated</td>
            </tr>
          </thead>
          <tbody>
            <tr v-for="(invoice_log, key) in invoice_logs" :key="key">
              <td>{{ key + 1 }}</td>
              <td>{{ invoice_log.invoice_no }}</td>
              <td>{{ invoice_log.entity }}</td>
              <td>{{ invoice_log.user_name }}</td>
              <td>
                {{ getFormattedDate(invoice_log.time, 'DD/MM/YYYY hh.mm a ') }}
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>

<script>
import { mapGetters, mapActions } from 'vuex';
import { required } from 'vuelidate/lib/validators';
import invoiceLoading from './LoadingComponent.vue';

export default {
  name: 'TheInvoiceView',
  components: { invoiceLoading },
  data() {
    return {
      submitted: false,
      loading_invoices: true,
      submit_status: false,
      response_status: true,
      sendyEntities: [],
      invoice_logs: [],
      sendyEntity: '',
      error_msg: '',
      generated_invoice_no: '',
    };
  },
  validations: {
    sendyEntity: { required },
  },
  computed: {
    ...mapGetters(['getSession']),
  },
  watch: {
    getSession(session) {
      return session;
    },
  },
  mounted() {
    this.fetchInvoiceLogs();
  },

  methods: {
    ...mapActions({
      request_invoice_data: 'request_invoice_data',
      perform_user_action: 'perform_user_action',
    }),

    async fetchInvoiceLogs() {
      this.submit_status = false;
      const payload = {
        app: 'CUSTOMERS_APP',
        endpoint: 'sendy/fetch_logs_entities',
        apiKey: true,
      };
      try {
        const res = await this.request_invoice_data(payload);
        const error = !this.status ? res.error : '';

        if (res.data.status) {
          this.loading_invoices = false;
          this.sendyEntities = res.data.entities;
          this.invoice_logs = res.data.logs;
        } else {
          this.loading_invoices = fail;
        }
      } catch (error) {
        this.loading_invoices = error;
      }
    },

    async generate_invoice_number() {
      this.submitted = true;
      this.$v.$touch();
      if (this.$v.$invalid) {
        return;
      }
      this.submit_status = true;
      this.response_status = true;

      const user_data = this.getSession.payload.data.name;

      const payload = {
        app: 'CUSTOMERS_APP',
        endpoint: 'sendy/cc_actions',
        apiKey: true,
        params: {
          channel: 'customer_support_peer_biz',
          data_set: 'cc_actions',
          action_id: 25,
          action_data: {
            entity_id: this.sendyEntity.entity_id,
          },
          request_id: '1622',
          action_user: user_data,
        },
      };
      try {
        const data = await this.perform_user_action(payload);

        if (data.status) {
          this.generated_invoice_no = data.invoice_no;
          this.response_status = 'success';

          setTimeout(() => {
            this.loading_invoices = true;
            this.fetchInvoiceLogs();
          }, 100000);
        } else {
          this.response_status = 'error';
          this.error_msg = data.message;
        }
      } catch (error) {
        this.response_status = 'error';
        this.error_msg =
          'Internal Server Error. Kindly refresh the page. If error persists contact tech support';
      }
    },
  },
};
</script>

<style lang="css" scoped>
.form-inline .form-control {
  width: 100%;
  border-radius: 0.25rem;
}
.form-inline {
  width: 50% !important ;
}
.form-inline .custom-select,
.form-inline .input-group {
  width: 100%;
  border-radius: 0.25rem;
}
.select {
  margin-left: -15px;
  padding: 0;
  width: 95%;
  height: 2%;
}
.user-input {
  margin-bottom: 15px;
}
.form-inline {
  margin-left: 2%;
}
.centre-loader {
  display: block;
  margin-left: auto;
  margin-right: auto;
  width: 50%;
}
.outline-inner-data {
  width: 100%;
}
.response-section {
  width: 95.5%;
  height: 55px;
  background: rgba(255, 255, 255, 0.91);
  border: 2px solid #00ae55;
  box-sizing: border-box;
  border-radius: 4px;
  margin-left: 2%;
  font-style: normal;
  font-weight: normal;
  font-size: 18px;
  line-height: 28px;
}
.invoice-loader--align {
  margin-left: 2%;
  margin-right: 1%;
}
.submit-success {
  color: #00ae55;
}
.submit-error {
  color: #ff0000;
}
.response-text {
  margin-top: 1%;
}
.invoice-number-highlight {
  color: #00ae55;
}
.table-content {
  max-width: 98%;
  margin-left: 1%;
  margin-top: 2%;
}
.table-background {
  background: #fff;
}
</style>
